package com.demo;

import static org.junit.Assert.assertFalse;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.demo.service.EmployeeService;

public class DemoApplicationTest {
	@Test
	public void testSomeLibraryMethod() {
		
	}
}
